services:
  redis:
    image: redis:latest
    container_name: redis_container
#    environment:
#      - REDIS_PASSWORD=${REDIS_PASSWORD}
#      - REDIS_USER=${REDIS_USER}
#      - REDIS_USER_PASSWORD=${REDIS_USER_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - bit_net

  fastapi_app:
    build: .
    container_name: fastapi_name_container
    entrypoint: ["/bin/bash", "/fastapi_app/app.sh"]
    ports:
      - 8000:8000
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
    networks:
      - bit_net
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:14.17-alpine3.21
    container_name: postgres_container
    environment:
      POSTGRES_USER:  ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bit_net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  bit_net:
    driver: bridge

volumes:
  redis_data:
    driver: local
  postgres_data:
    driver: local